#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'daemons'

opts = {
  :app_name => "echofollow", 
  :backtrace => true, 
  :ontop => false, 
#  :monitor => true, 
  :log_output => true
}

cwd = File.dirname(File.expand_path(__FILE__))
Daemons.run(cwd+"/#{opts[:app_name]}.rb", opts)

exit 0
